description = "Base image (Ubuntu Jammy Jellyfish build image, distroless-like run image) with only Node buildpacks included. To use, specify buildpacks at build time."

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/nodejs:9.5.0"
  version = "9.5.0"

[lifecycle]
  version = "0.20.13"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nodejs"
    version = "9.5.0"

[stack]
  build-image = "docker.io/paketobuildpacks/build-jammy-full:0.3.519"
  id = "io.buildpacks.stacks.jammy.full"
  run-image = "index.docker.io/paketobuildpacks/run-jammy-full:latest"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
