description = "ARM64 Jammy Tiny-ish builder with Paketo Node"

[stack]
id = "io.buildpacks.stacks.jammy.tiny"
build-image = "jonathank4/build-jammy-tiny-arm64"
run-image   = "jonathank4/run-jammy-tiny-arm64"

[lifecycle]
version = "0.20.13"

[[buildpacks]]
id  = "jonathank4/node-engine-arm64"
uri = "jonathank4/node-engine-arm64:latest"

[[order]]
  [[order.group]]
  id = "jonathank4/node-engine-arm64"

[[targets]]
arch = "arm64"
os   = "linux"

