description = "ARM64 Jammy Tiny-ish builder with Paketo Node"

[stack]
id = "io.buildpacks.stacks.jammy.tiny"
build-image = "localhost:5000/build-jammy-tiny-arm64"
run-image   = "localhost:5000/run-jammy-tiny-arm64"

[lifecycle]
version = "0.20.13"

[[buildpacks]]
id  = "k4connect/node-engine-arm64"
uri = "localhost:5000/node-engine-arm64-bp:1.0.0"

[[order]]
  [[order.group]]
  id = "k4connect/node-engine-arm64"

[[targets]]
arch = "arm64"
os   = "linux"

